### ISSUE TITLE
How to extract the optimal vectors and optimal values?

### ISSUE THREAD

**Issue by sivabkumar** [ImperialCollegeLondon/DirectSearch.jl#19]
obj(x) = x'*[2 1;1 4]*x + x'*[1;4] + 7;
p = DSProblem(2; objective=obj, initial_point=[1.0,2.0]);
Optimize!(p)

The above code produces the output.

But how to get the x[1] and x[2] values and the optimal values to create a dataframe?

**Comment by mzagorowska** [comment]
Optimal solution: `p.x` and optimal value: `p.x_cost`. 

In general the following options are available:
![image](https://github.com/ImperialCollegeLondon/DirectSearch.jl/assets/7868389/47b62d07-1367-4bd6-93da-d24347029bc0)

**Comment by sivabkumar** [comment]
Dear Professor,
Thank you for you timely response.
Regards 
Dr. B. Sivakumar Ph.D., Associate Professor, Department of Applied Mathematics and Statistics, School of Mathematics, Madurai Kamaraj University, Madurai - 625 021, Tamilnadu, India. Mobile: +91 98942 27177 

    On Friday, May 17, 2024 at 11:32:58 AM GMT+5:30, mzagorowska ***@***.***> wrote:  
 
 


Optimal solution: p.x and optimal value: p.x_cost.

In general the following options are available:
image.png (view on web)
